Pandas Series

In [4]:
import pandas as pd

myDict = {
    'name': ['a', 'b', 'c', 'd'],
    'class': ['EEE', 'ECE', 'CSE', 'CE']
}

s1 = pd.Series(myDict)
print(s1)
print(type(s1))

name            [a, b, c, d]
class    [EEE, ECE, CSE, CE]
dtype: object
<class 'pandas.core.series.Series'>

In [5]:
L = [0, 1, 2, 3, 4, 5]

s2 = pd.Series(L)
print(s2)
print(type(s2))

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
<class 'pandas.core.series.Series'>

In [11]:
#Accessing
print(s1['name'])
print('-'*30)
print(s2[0:2])

['a', 'b', 'c', 'd']
------------------------------
0    0
1    1
dtype: int64

Pandas DataFrame

In [12]:
cols = ['a', 'b', 'c', 'd']
List = [
    [1, 2, 3, 4],
    [4, 3, 2, 1],
    [5, 6, 7, 8],
    [9, 8, 7, 6]
]

df = pd.DataFrame(List, columns=cols)
df

   a  b  c  d
0  1  2  3  4
1  4  3  2  1
2  5  6  7  8
3  9  8  7  6

In [13]:
Dict = {
        'Subject': ['Maths', 'Physics', 'Chemistry'],
        'Marks'  : [60, 50, 57]
        }

df = pd.DataFrame(Dict)

df['Percentage'] = round(df['Marks'] * 100 / 70, 2)

df

     Subject  Marks  Percentage
0      Maths     60       85.71
1    Physics     50       71.43
2  Chemistry     57       81.43

In [14]:
cols = ('employee', 'salary')
tup = [
    ('akshat', '4000'),
    ('vidhi', '5000'),
    ('aman', '6000')
]

df = pd.DataFrame(tup, columns=cols)
df

  employee salary
0   akshat   4000
1    vidhi   5000
2     aman   6000

In [15]:
list_of_dict = [
    {"Name": "Akshat", "Marks": 80},
    {"Name": "Rahul", "Marks": 90},
    {"Name": "Aman", "Marks": 75}
]

df = pd.DataFrame(list_of_dict)
df

     Name  Marks
0  Akshat     80
1   Rahul     90
2    Aman     75

Data Iteration

In [23]:
data = {
    'Name': ['Akshat', 'Rahul', 'Aman', 'Riya'],
    'Marks': [80, 90, 75, 60],
    'City': ['Jaipur', 'Delhi', 'Mumbai', 'Jaipur']
}

df = pd.DataFrame(data)
df

     Name  Marks    City
0  Akshat     80  Jaipur
1   Rahul     90   Delhi
2    Aman     75  Mumbai
3    Riya     60  Jaipur

In [25]:
print(df[df['Marks'] > 70])
print(f"\n{'-'*30}\n")
print(df[df['City'] == 'Jaipur'])

     Name  Marks    City
0  Akshat     80  Jaipur
1   Rahul     90   Delhi
2    Aman     75  Mumbai

------------------------------

     Name  Marks    City
0  Akshat     80  Jaipur
3    Riya     60  Jaipur

In [33]:
print(df.iloc[0])
print(f"\n{'-'*30}\n")
print(df.iloc[2:4])

Name     Akshat
Marks        80
City     Jaipur
Name: 0, dtype: object

------------------------------

   Name  Marks    City
2  Aman     75  Mumbai
3  Riya     60  Jaipur

In [35]:
print(df.loc[0:1, 'Name'])
print(f"\n{'-'*30}\n")
print(df.iloc[0:2, 0:2])

0    Akshat
1     Rahul
Name: Name, dtype: object

------------------------------

     Name  Marks
0  Akshat     80
1   Rahul     90

In [36]:
res = df[df['Marks'] >= 70]

print(res)

     Name  Marks    City
0  Akshat     80  Jaipur
1   Rahul     90   Delhi
2    Aman     75  Mumbai

In [40]:
row = df.iloc[0].tolist()
row

['Akshat', 80, 'Jaipur']